WebQuanLyBanHang/Models/PagingViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebQuanLyBanHang.Data.Entity;

namespace WebQuanLyBanHang.Models
{
    public class PagingViewComponent: ViewComponent
    {
         dynamic model;
         public PagingViewComponent()
         {
           
         }
        public IViewComponentResult Invoke()
        {
            this.model = model;
            return View(model);
        }
    }
}

WebQuanLyBanHang/Controllers/ProductTypeController.cs
using Microsoft.AspNetCore.Mvc;
using WebQuanLyBanHang.Service.Interface;
using WebQuanLyBanHang.Utilities.ViewModel;
using WebQuanLyBanHang.Utilities;

namespace WebQuanLyBanHang.Controllers
{
    public class ProductTypeController : BaseController
	{
        private readonly IClassifyProductService _classifyProductService;
        public ProductTypeController(IClassifyProductService classifyProductService)
        {
            _classifyProductService = classifyProductService;
        }
        [HttpGet]
        [Route("loai-san-pham")]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Table(Pageding pageding)
        {
            var data = await _classifyProductService.GetAll(pageding);
            return View(data);
        }
        [HttpPost]
        public async Task<IActionResult> Add([FromBody] ClassifyProductVM model)
        {
            /// Thêm mới khi id = 0
            if (model.Id < 1)
            {
                await _classifyProductService.Add(model);
            }
            else
            {
                await _classifyProductService.Update(model);
            }

            return Ok(model.Id);
        }
        [HttpGet]
        public async Task<IActionResult> GetModel(int id)
        {
            var data = await _classifyProductService.Get(id);
            return Ok(data);
        }
        [HttpGet]
        public async Task<IActionResult> CheckData(string keyword)
        {
            var data = await _classifyProductService.CheckData(keyword);
            return Ok(data);
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            await _classifyProductService.Delete(id);
            return Ok();
        }
    }
}

WebQuanLyBanHang/Views/ProductType/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- [ Main Content ] start -->
<!-- [ Main Content ] start -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Loại sản phẩm</h1>
    <p class="mb-4">
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Nhập từ khóa tìm kiếm" id="searchkeyword">
            <button onclick="search()" class="btn btn-outline-secondary" type="button" id="button-addon2"><i class="fa fa-search" aria-hidden="true"></i></button>
        </div>
    </p>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"></h6>
            <button onclick="openmodal()" style="float:right" type="button" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> Thêm mới</button>
        </div>
        <div class="card-body">
            <div id="table-data">
                <div class="card-body">
                    <div class="spinner-grow text-primary" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                    <div class="spinner-grow text-secondary" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                    <div class="spinner-grow text-success" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                    <div class="spinner-grow text-danger" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                    <div class="spinner-grow text-warning" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                    <div class="spinner-grow text-info" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                    <div class="spinner-grow text-light" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                    <div class="spinner-grow text-dark" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>



<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Thêm mới</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <input type="hidden" id="idhide" />
                    <label for="recipient-name" class="col-form-label">Loại sản phẩm</label>
                    <input type="text" class="form-control" id="nameproduct">
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" onclick="save()" class="btn  btn-primary" title="Lưu lại">
                    <i class="fa fa-cloud" aria-hidden="true"></i>
                </button>
                <button type="button" class="btn  btn-secondary" data-dismiss="modal" title="Đóng lại">
                    <i class="fa fa-times-circle" aria-hidden="true"></i>
                </button>

            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">

        let pagenum = 0;

        $(document).ready(function () {
            load(1, null);
            pagenum = 1;
            Reset();
        });
        function openmodal() {
            $('#exampleModal').modal();
            Reset();
        }

        // Load data
        function load(i, keyword) {
            axios.get('@Url.Action("Table", "ProductType")', {
                params: {
                    //  pageding: datas
                    KeyWord: keyword,
                    PageNum: i,
                    PageSize: 8,
                }
            })
                .then(function (response) {
                    $("#table-data").html(response.data);
                })
                .catch(function (error) {
                    $.notify(error, "error");
                })
        }
        //
        let ckdata;
        function checkdata() {
            axios.get('@Url.Action("CheckData", "ProductType")', {
                params: {
                    keyword: $("#nameproduct").val()
                }
            })
                .then(function (response) {
                    if (response.data == true) {
                        ckdata = false;
                        CreateValidate('#nameproduct', 'Tên đã bị trùng!')
                    } else {
                        ckdata = true;
                        ClearError('#nameproduct');
                    }

                })
                .catch(function (error) {
                    $.notify(error, "error");

                })
        }
        //
        function nextpage(i) {
            pagenum = i;
            load(i, $("#searchkeyword").val());
        }
        //
        function search() {
            load(pagenum, $("#searchkeyword").val());
        }
        //
        /// Hàm resert các đầu nhập vào //
        function Reset() {
            $("#nameproduct").val(null);
            $("#idhide").val(0);
            //Xóa lỗi
            ClearError('#nameproduct');

        }
        //
        function validatefrom() {
            FormModalIsValid = true;
            ValidateRequireControl('#nameproduct', 'Bạn phải nhập tên trạng thái!');
            ValidateRequireControlMaxLength('#nameproduct', 'Đã vượt qua 256 ký tự', 256);
        }
        //
        function edit(id) {
            axios.get('@Url.Action("GetModel", "ProductType")', {
                params: {
                    id: id
                }
            })
                .then(function (response) {
                    $('#exampleModal').modal('show');
                    $("#nameproduct").val(response.data.name);

                    $("#idhide").val(response.data.id);
                })
                .catch(function (error) {
                    $.notify(error, "error");
                });
        };
        function del(id) {
            Swal.fire({
                title: 'Bạn chắc chắn muốn xóa?',
                // text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Đồng ý',
                cancelButtonText: "Quay lại",
            }).then((result) => {
                if (result.isConfirmed) {
                    axios.delete('@Url.Action("Delete", "ProductType")', {
                        params: {
                            id: id
                        }
                    }).then(response => {
                        if (response.status == 200) {
                            Swal.fire(
                                'Xóa!',
                                'Bạn đã xóa bỏ 1 bản ghi',
                                'success',
                            )

                        } else {
                            $.notify(error, "Loại này đang sử dụng!");
                        }
                        load(1, null);
                    });

                }

            });
        };
        //save
        function save() {
            validatefrom();
            if (FormModalIsValid) {
                axios
                    .post('@Url.Action("Add", "ProductType")', {
                        // Data to be sent to the server
                        id: $("#idhide").val(),
                        name: $("#nameproduct").val(),
                    })
                    .then(response => {
                        if (response.data < 1) {
                            $.notify("Thêm mới thành công!", "success");
                        }
                        else {
                            $.notify("Chỉnh sửa thành công!", "success");
                        }
                        load(1, null);
                        $('#exampleModal').modal('hide');
                    })
                    .catch(function (error) {
                        $.notify(error, "error");
                    });
            }
        }
    </script>
}

WebQuanLyBanHang/Views/ProductType/Table.cshtml
@using WebQuanLyBanHang.Utilities.ViewModel;
@using WebQuanLyBanHang.Utilities;
@model ResponseData<ClassifyProductVM>
    @{
        ViewData["Title"] = "Index";
        Layout = null;
    }

    <div class="card-body table-border-style">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Stt</th>
                        <th>Loại sản phẩm</th>
                        <th class="text-center">Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Items)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Name</td>
                            <td class="text-center">
                            <button class="btn btn-success" onclick="edit('@item.Id')" title="Sửa">
                                <i class="fa fa-wrench" aria-hidden="true"></i>
                                Sửa</button>
                            <button class="btn btn-danger" onclick="del('@item.Id')" title="Xóa">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                                Xóa</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div>
                @await Component.InvokeAsync("Paging", Model)
            </div>
        </div>
    </div>